### ISSUE TITLE
Exchange won't connect with MFA

### ISSUE THREAD

**Issue by nikkelly** [nikkelly/microsoftServicesProfile#8]
Have credentials saved 
Have MFA status saved
Attempted to connect with "Exchange" and run `Get-EXORecipient` but got this error:

```
New-ExoPSSession : One or more errors occurred.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSess
   ion
```

Used `Connect-ExchangeOnline` and then completed interactive login.

**Comment by greenspace4ever** [comment]
@nikkelly Is it spelled Connect-**Exchnage**Online in the documentation? Might there be a spelling or syntax error?

**Comment by nikkelly** [comment]
> @nikkelly Is it spelled Connect-**Exchnage**Online in the documentation? Might there be a spelling or syntax error?

Good catch! Updated the typos in the issue - I used it correctly in PowerShell but was just in a hurry when opening the issue 😄
